// timezoneNames.js
module.exports = {
    "GMT": "Greenwich Mean Time",
    "GMT+1": "Greenwich Mean Time +1",
    "UTC": "Coordinated Universal Time",
    "BST": "British Summer Time",
    "CET": "Central European Time",
    "CEST": "Central European Summer Time",
    "EET": "Eastern European Time",
    "EEST": "Eastern European Summer Time",
    "MSK": "Moscow Time",
    "MSD": "Moscow Summer Time",
    "IST": "Indian Standard Time",
    "SGT": "Singapore Time",
    "JST": "Japan Standard Time",
    "AEST": "Australian Eastern Standard Time",
    "AEDT": "Australian Eastern Daylight Time",
    "NZST": "New Zealand Standard Time",
    "NZDT": "New Zealand Daylight Time",
    "PST": "Pacific Standard Time",
    "PDT": "Pacific Daylight Time",
    "MST": "Mountain Standard Time",
    "MDT": "Mountain Daylight Time",
    "CST": "Central Standard Time",
    "CDT": "Central Daylight Time",
    "EST": "Eastern Standard Time",
    "EDT": "Eastern Daylight Time",
    "AKST": "Alaska Standard Time",
    "AKDT": "Alaska Daylight Time",
    "HST": "Hawaii Standard Time",
    "HAST": "Hawaii-Aleutian Standard Time",
    "HADT": "Hawaii-Aleutian Daylight Time",
    "SST": "Samoa Standard Time",
    // ... rest of the timezones
};